// Automatically generated by config_to_header.py
#ifndef __KCONFIG_H__
#define __KCONFIG_H__

#define PROJECT_NAME "apm32-project"
#define PROJECT_VERSION "0.0.1"
#define FreeRTOS 1
#define LED 1
#define APM32F405 1
#define Flash 1

#endif // __KCONFIG_H__